### ISSUE TITLE
refresh_leds spike at 600 ms

### ISSUE THREAD

**Issue by SebastianRoll** [SebastianRoll/rhyth_sic_game#3]
Function refresh_leds Time = 559.988ms
Function refresh_outer_leds Time =  0.848ms
Function tick_animation Time =  1.992ms
Function refresh_leds Time =  8.554ms
Function refresh_outer_leds Time =  0.778ms
Function tick_animation Time =  1.988ms
Function refresh_leds Time =  8.431ms
Function refresh_outer_leds Time =  0.780ms
Function tick_animation Time =  1.209ms
Function refresh_leds Time =  8.369ms
Function refresh_outer_leds Time =  0.790ms

**Comment by SebastianRoll** [comment]
Happens on frame 441

```
>>> menu.r.o
441
```

```
>>> menu.r.o
878
```

**Comment by SebastianRoll** [comment]
Exception: Function get_beat_positions Time = 554.432ms

**Comment by SebastianRoll** [comment]
```
songs/I know You know/Medium.b
Function refresh_leds Time = 573.561ms
Game over! Score: -5
Function refresh_leds Time = 573.561ms
cleaning up..
Traceback (most recent call last):
  File "<stdin>", line 132, in <module>
  File "<stdin>", line 129, in <module>
  File "<stdin>", line 85, in play
  File "<stdin>", line 79, in play
  File "rhyth_game_sync.py", line 188, in play_song
  File "rhyth_game_sync.py", line 188, in play_song
  File "rhyth_game_sync.py", line 155, in play_song
  File "utils.py", line 12, in new_func
Exception: Function refresh_leds Time = 573.561ms
```

**Comment by SebastianRoll** [comment]
Exception: Function get_beat_positions Time = 554.828ms
>>> menu.r.o
877
